### ISSUE TITLE
Props

### ISSUE THREAD

**Issue by uptownhr** [rill-js/rill#12]
Not react props. I just wanted to give you some props for making this. I've been thinking about how great it would be if this existed and attempted once. But got too tricky for me trying to extrapolate express routes for the browser. I'll be following closely!

Funny story as well, I put something together last week, less of a framework but something that puts together webpack and hmr together for ssr. Not complete but works given the right conditions right now. Need to add in configurability. checkout, http://github.com/uptownhr/kube. 

Right now, i'm trying to see how I can use rill, instead of express and see where that can go.

**Comment by DylanPiercey** [comment]
@uptownhr thanks for the props! I'm glad that Rill was generally well received, I have been working on it a ton in my spare time for the past year and a half (check out the number of middleware!). I'm glad to say that it is used in ~15 simple ish websites, 1 cms and another app.

For context I was originally inspired by https://github.com/matthewwithanm/monorouter which showed me that this concept could be taken all the way. I took a different approach though, one that I quite like. [@rill/http](https://github.com/rill-js/http) is the core of this library and it isn't the craziest thing to grok. In fact there isn't one part of this repo that refers to anything in the browser. Rill could be a standalone nodejs framework, the only ties to the browser is that it uses [@rill/http](https://github.com/rill-js/http) and that it doesn't try to do some crazy server only stuff.

Certainly feel free to ask me any questions about Rill or how I use it to build apps in the gitter chat, i'd love to know how others use it.

**Comment by DylanPiercey** [comment]
Closing this, feel free to chat on the gitter about your progress.

**Comment by DylanPiercey** [comment]
@uptownhr, thanks again for trying Rill.

I am trying to improve to documentation and lower the barrier to entry to the project and am wondering what issues you ran into, if you still use Rill and what things you think I have failed to mention in the docs about the project?

Answering these questions would be a huge help!

**Comment by uptownhr** [comment]
Will do. Actually has been a while since I've tried Rill so I'm going to take a look at the docs again. 

Just did that. First feeling I get is that I don't feel like I'm seeing a universal example. I wish it can explicitly show the code running from the server-side and the client-side. I understand you're trying to be brief but it is a lot to take in and imagine. 


Outside of documentation
1. One great item I'd recommend taking your time on is a generator script. Something to get a boiler plate up.
2. Probably very easy to do, but implementing or showing how layouts can be done would be nice. 

I'll keep adding on here as I think of more items.
