### ISSUE TITLE
Documentation: Transpiling JSX / React

### ISSUE THREAD

**Issue by Srirangan** [rill-js/rill#16]
The main example on the readme would not work without a step that transpiles JSX / React.

I'll submit a PR as soon as (and if) I figure out an easy way to do that.

PS: Thanks, the concept of this framework is quite exciting. I'll be playing with it quite a bit over my weekends. 👍

**Comment by DylanPiercey** [comment]
Hey,

I'm glad you find it interesting. I think most people nowadays are using
some kind of module bundler (browserify/webpack/rollup). In the example I
mention that you need Babel, but there are a few ways to run Rill without
transpiling, but I wouldn't not recommend for production.

Let me know if you find anything interesting out though, and feel free to
message me on the gitter if you have any questions, problems or just want
to chat about Rill.
