### ISSUE TITLE
Pass the request, response and next() arguments to the middlewares

### ISSUE THREAD

**Issue by imolorhe** [rill-js/rill#19]
Hello,

Is it possible that the `re`, `res`, `next()` arguments can be passed directly to the controllers as arguments? To streamline it with the approach taken by express. Currently the first argument is the context while the second is the next() when available.

**Comment by DylanPiercey** [comment]
Hey @imolorhe.

Rill, much like [koa](https://github.com/koajs/koa), is designed with the future of javascript in mind. The reason why everything is bundled under context is to keep the function signature for middleware simple.

The best way to use the context is to pull out properties using es2015 argument destructuring. Like so:

```js
app.get(({ req, res, locals }, next) => ...)
``` 

The other big benefits here are that there can be much more than 'req' and 'res' (notice locals) making the context more flexible without polluting those existing objects.

I think this is best for the library to keep the signature as is but I certainly welcome all feedback and if you have any other ideas or questions please bring them forward 😀.
