### ISSUE TITLE
Res.status returns 404 when using promises in routes

### ISSUE THREAD

**Issue by imolorhe** [rill-js/rill#20]
Hello,

The response object returns a 404 whenever I use promises with the routes. When I remove the promise, the response is resolved normally. The examples on the site are done with async/await, so I think that is likely the issue. Is there any example using regular promises?

**Comment by DylanPiercey** [comment]
Hey,

Thanks for your question. If you didn't mind providing a code snippet that would be a huge help.
Here is an arbitrary example of using Rill with vanilla promises.

```js
require('isomorphic-fetch')

app.get('/home', (ctx) => {
  return fetch('http://google.ca')
    .then(response => response.text())
    .then(html => {
      ctx.res.body = html
    })
})
```

**Comment by imolorhe** [comment]
@DylanPiercey I have something like that too. At what point is the status set? When the `ctx.res.body` is set?

**Comment by DylanPiercey** [comment]
If the body is non empty the status will default to 200. You can also manually set `ctx.res.status = 200`.

**Comment by imolorhe** [comment]
@DylanPiercey So the promise needs to be returned for it to properly resolve.

**Comment by DylanPiercey** [comment]
@imolorhe that is correct, otherwise Rill has no idea when the promise finishes.

**Comment by imolorhe** [comment]
@DylanPiercey Okay so what exactly determines the value of `ctx.res.status`? Is it setting the value of `ctx.res.body`? Or there is another condition that is applied? I am asking this because it seems I am getting 404 even without a promise involved.

**Comment by DylanPiercey** [comment]
ctx.res.status will only automatically set if there is a ctx.res.body, if there is a ctx.res.body it will default to 200. Otherwise it is 404 unless explicitly set by the user.

**Comment by imolorhe** [comment]
@DylanPiercey Thanks! I know it's probably too much to ask, but what is the promise-based equivalent of this snippet:

```js
app.use(async (ctx, next)=> {
  try {
    await next()
  } catch (error) {
    // Catch errors later on in the stack.
    log.error('server error', err)
  }
})
```

**Comment by DylanPiercey** [comment]
@imolorhe no problem -

```js
app.use((ctx, next) => {
  return next().catch((err) => {
    log.error('server error', err)
  })
})
```

**Comment by DylanPiercey** [comment]
@imolorhe i'm going to close this for now. Hit me up on gitter if you have any other questions regarding this or promises 😄.

**Comment by imolorhe** [comment]
@DylanPiercey Okay
